######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 18 23:02:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
